### PR TITLE
refactor(urls): update URLs to be consistent with latest communicator version

### LINKED ISSUE #79: Update to New Communicator
A new version of the communicator with the new service URLs is soon to be released. We need to upgrade to that version for login to work correctly.

We will also need to update `environments-service.js` at the same time:

```js
    function getTokensAPI(environment, useOldToken) {
      if (useOldToken) {
        return environment.TOKEN_SERVICE + '/tokens'; // TODO change to old key
      } else {
        return environment.USER_SERVICE_NEW + '/tokens'; // TODO change to new key
      }
    }
```

### PR DESCRIPTION
**Pull request by cjhowald**
Fixes #79

### CODE REVIEW

**Comment by frontendherodk** [comment]
👍

**Comment by cjhowald** [comment]
@frontendherodk No longer WIP, updated the communicator version. Please review again.

**Comment by frontendherodk** [comment]
👍

**Comment by cjhowald** [comment]
👍

**Pull request merged**
