### PR TITLE
Feature/56 ignore user agent check localhost

### LINKED ISSUE #56: Changing user agent shouldn't logout the user in development
@frontendherodk requested this change on SC. As he noted, the issue belongs here.

Original text:

> Logging out the user when changing the user agent is a big pain point for development. Especially when you're working with styles.

> We should look into if this is needed at all, and if yes, then disable it while working in localhost

For total removal, a conversation needs to be had regarding why the user agent check was implemented and what the repercussions of its removal are. Removing for localhost is probably okay.

### PR DESCRIPTION
**Pull request by gregdeane**
* Code is on [Integration](https://sc-integration.norris.zalan.do)
* Refactored tests as well as added missing tests
* Refactored services to conform in `IIFE`/`$inject` style

To test (localhost):
1. `bower link` solution-center-login to SC
1. Use Chrome dev tools to emulate an iPhone.
1. Reload the page.
1. You should **not** be logged out.
1. Switch back to standard browser mode.
1. You should **not** be logged out.

To test (integration):
1. Use Chrome dev tools to emulate an iPhone.
1. Reload the page.
1. You **should** be logged out.
1. Log back in.
1. Switch back to standard browser mode.
1. You **should** be logged out. 

Closes #56

### CODE REVIEW

**Comment by gregdeane** [comment]
@frontendherodk Please give this a review when you have time. Please test in both local and integration. This should solve the issue but let me know if it doesn't

**Comment by cjhowald** [comment]
Please revert `dist` changes

**Comment by gregdeane** [comment]
`dist` reverted.

**Comment by cjhowald** [comment]
Nice job refactoring and improving the tests. 100% coverage!

**Comment by cjhowald** [comment]
Manual and unit tests pass.

**Comment by cjhowald** [comment]
👍

**Comment by gregdeane** [comment]
👍

**Pull request merged**
