### PR TITLE
Feature/update module name 30

### LINKED ISSUE #30: Change angular services naming
authenticationService, ENVIRONMENTS and environmentsService are to common names, there is a risk to overwrite services registered in the user app.

I would suggest to use ```sc``` as a prefix.

authenticationService -> scAuthenticationService
environmentsService -> scEnvironmentsService
ENVIRONMENTS -> SC_ENVIRONMENTS

### PR DESCRIPTION
**Pull request by gregdeane**
Closes #30 

This release will be `major` with breaking changes regarding the module/component names.

### CODE REVIEW

**Comment by dami-gg** [comment]
:+1:

**Comment by gregdeane** [comment]
thumbs downing to prevent merge until tomorrow.

**Comment by gregdeane** [comment]
👎

**Comment by gregdeane** [comment]
👍

**Pull request merged**
